# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

stages:
  - build
  - deploy

image:
    name: quay.io/singularity/singularity:v3.8.4
    entrypoint: [ "" ]

tags:
    - docker7


.templateBuild:
  stage: build
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - singularity build container.sif $RECIPE_PATH/Singularity.$BASENAME-$TAG


#####################
## Quality control
#####################


fastqc-0119-build:
  extends: .templateBuild
  variables:
    BASENAME: fastqc
    TAG: 0119
    RECIPE_PATH: recipes/quality-control/fastqc/

