# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

stages:
  - build
  - deploy

image:
    name: quay.io/singularity/singularity:v3.8.4
    entrypoint: [ "" ]


.templateBuild:
  stage: build
  allow_failure: false
  tags:
    - docker7
  script:
    - singularity build container.sif $RECIPE_PATH/Singularity.$BASENAME-$TAG


.templateDeploy:
  stage: deploy
  tags:
    - docker7
  script:
    - singularity push --docker-username gitlab-ci-token --docker-password $CI_JOB_TOKEN container.sif oras://"$CI_REGISTRY_IMAGE"/$BASENAME:$TAG

#####################
## Quality control
#####################


fastqc-0119-build:
  extends: .templateBuild
  variables:
    BASENAME: fastqc
    TAG: 0119
    RECIPE_PATH: recipes/quality-control/fastqc/
  only:
    changes:
      - recipes/quality-control/fastqc/Singularity.fastqc-0119


fastqc-0119-deploy:
  extends: .templateDeploy
  needs: [fastqc-0119-build]
  variables:
    BASENAME: fastqc
    TAG: 0119
