# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

stages:
  - buildPushImage


.template:
  stage: buildPushImage
  tags:
    - docker7
  image:
    name: quay.io/singularity/singularity:v3.8.4
    entrypoint: [ "" ]
  script:
    - singularity build container.sif $RECIPE_PATH/Singularity.$BASENAME-$TAG
    - singularity push --docker-username gitlab-ci-token --docker-password $CI_JOB_TOKEN container.sif oras://"$CI_REGISTRY_IMAGE"/$BASENAME:$TAG



#####################
## Quality control
#####################


fastqc-0119:
  extends: .template
  variables:
    BASENAME: fastqc
    TAG: 0119
    RECIPE_PATH: recipes/quality-control/fastqc/
  only:
    refs:
      - main
    changes:
      - recipes/quality-control/fastqc/Singularity.fastqc-0119
