# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

stages:
  - test
  - builddeploy

image:
    name: quay.io/singularity/singularity:v3.8.4
    entrypoint: [ "" ]


.templateTest:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  tags:
    - docker7
  script:
    - singularity build container.sif $RECIPE_PATH/Singularity.$BASENAME-$TAG


.templateBuildDeploy:
  stage: builddeploy
  tags:
    - docker7
  only:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE == "deploy"
  script:
    - singularity build container.sif $RECIPE_PATH/Singularity.$BASENAME-$TAG
    - singularity push --docker-username gitlab-ci-token --docker-password $CI_JOB_TOKEN container.sif oras://"$CI_REGISTRY_IMAGE"/$BASENAME:$TAG

#####################
## Submission area
#####################


#fastqc-0119cv7-test:
#  extends: .templateTest
#  variables:
#    BASENAME: fastqc
#    TAG: 0119cv7
#    RECIPE_PATH: recipes/quality-control/fastqc/


#fastqc-0119cv8-test:
#  extends: .templateTest
#  variables:
#    BASENAME: fastqc
#    TAG: 0119cv8
#    RECIPE_PATH: recipes/quality-control/fastqc/

#####################
## Quality control
#####################

fastqc-0119cv7-builddeploy:
  extends: .templateBuildDeploy
  variables:
    BASENAME: fastqc
    TAG: 0119cv7
    RECIPE_PATH: recipes/quality-control/fastqc/
  only:
    changes:
      - recipes/quality-control/fastqc/Singularity.fastqc-0119cv7


fastqc-0119cv8-builddeploy:
  extends: .templateBuildDeploy
  variables:
    BASENAME: fastqc
    TAG: 0119cv8
    RECIPE_PATH: recipes/quality-control/fastqc/
  only:
    changes:
      - recipes/quality-control/fastqc/Singularity.fastqc-0119cv8
