# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

stages:
  - test
  - builddeploy

image:
    name: quay.io/singularity/singularity:v3.8.4
    entrypoint: [ "" ]


.templateTest:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  tags:
    - docker7
  script:
    - singularity build container.sif $RECIPE_PATH/Singularity.$BASENAME-$TAG


.templateBuildDeploy:
  stage: builddeploy
  tags:
    - docker7
  script:
    - singularity build container.sif $RECIPE_PATH/Singularity.$BASENAME-$TAG
    - singularity push --docker-username gitlab-ci-token --docker-password $CI_JOB_TOKEN container.sif oras://"$CI_REGISTRY_IMAGE"/$BASENAME:$TAG

#####################
## Quality control
#####################


fastqc-0119-test:
  extends: .templateBuild
  variables:
    BASENAME: fastqc
    TAG: 0119
    RECIPE_PATH: recipes/quality-control/fastqc/
    expire_in: 3 days

fastqc-0119-builddeploy:
  extends: .templateBuildDeploy
  variables:
    BASENAME: fastqc
    TAG: 0119
    RECIPE_PATH: recipes/quality-control/fastqc/
  only:
    changes:
      - recipes/quality-control/fastqc/Singularity.fastqc-0119


