# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

stages:
  - test
  - builddeploy

image:
    name: quay.io/singularity/singularity:v3.8.4
    entrypoint: [ "" ]


.templateTest:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  tags:
    - docker7
  script:
    - singularity build container.sif $RECIPE_PATH/Singularity.$BASENAME-$TAG


.templateBuildDeploy:
  stage: builddeploy
  tags:
    - docker7
  only:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - singularity build container.sif $RECIPE_PATH/Singularity.$BASENAME-$TAG
    - singularity push --docker-username gitlab-ci-token --docker-password $CI_JOB_TOKEN container.sif oras://"$CI_REGISTRY_IMAGE"/$BASENAME:$TAG

#####################
## Submission area
#####################

## WRITE YOUR TEST RULE HERE AFTER BRANCHING ON SUBMISSION AND CREATE A MERGE REQUEST


#####################
## Include
#####################

include:

  #####################
  # Quality control
  #####################
  - local: "yaml-files/quality-control/fastqc-deploy.yaml"

  #####################
  # fastq operations
  #####################
  - local: "yaml-files/fastq-operations/parallelfastqdump-deploy.yaml"

  #####################
  # Analysis suites
  #####################
  - local: "yaml-files/analysissuites/deeptools-deploy.yaml"
  - local: "yaml-files/analysissuites/samtools-deploy.yaml"
  - local: "yaml-files/analysissuites/picardtools-deploy.yaml"

  #####################
  # Mapping
  #####################
  - local: "yaml-files/mapping/bowtie2-deploy.yaml"
  
   #####################
   # Peaks callers
   #####################
  - local: "yaml-files/peakcallers/hiddendomains-deploy.yaml"
  - local: "yaml-files/peakcallers/macs2-deploy.yaml"

   #####################
   # Others
   #####################
  - local: "yaml-files/image-analysis/deeplabcut-deploy.yaml"

